I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 112, in script
    show login with dissolve
AttributeError: 'float' object has no attribute 'visit_all'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 112, in script
    show login with dissolve
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 1678, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\exports.py", line 1757, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 2975, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 3579, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 4052, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\screen.py", line 481, in visit_all
    self.child.visit_all(callback, seen=None)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Wampl\Documents\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 3 more times]
AttributeError: 'float' object has no attribute 'visit_all'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
LyteLove v1 1.1
Thu Dec 28 20:41:34 2023
